### ISSUE TITLE
Error with v2.0.17 and later of the framework

### ISSUE THREAD

**Issue by rlowry** [LearningPool/adapt-contrib-openTextInput#27]
It looks like the following change to the Adapt Framework in v2.0.17 may have broken this component.

https://github.com/adaptlearning/adapt_framework/issues/1429

See screenshot below for error shown on clicking the **Submit** button:

[![](http://i.imgur.com/Iq8mCrM.png)](http://i.imgur.com/Iq8mCrM.png)

**Comment by brian-learningpool** [comment]
Hi @rlowry, thanks for raising.  I'm seeing the same issue.

**Comment by brian-learningpool** [comment]
@rlowry, this should be resolved in https://github.com/LearningPool/adapt-contrib-openTextInput/pull/29.  Can you test the `issue/27` branch?

**Comment by rlowry** [comment]
@brian-learningpool That's resolved it for me. Thanks for fixing so quickly!

**Comment by brian-learningpool** [comment]
No problem, thank you for raising the issue.

Resolved in version [1.2.0](https://github.com/LearningPool/adapt-contrib-openTextInput/releases/tag/1.2.0).
