### ISSUE TITLE
AT-1040 - Open text input not displaying correctly within interactive video extension

### ISSUE THREAD

**Issue by kilianLearningPool** [LearningPool/adapt-contrib-openTextInput#43]
The open text input extension is not displaying correctly on the interactive video component. If you enter text into the open text input field and click Submit, the input box does not resize to fit all of the feedback text 
<img width="716" alt="screen shot 2019-03-07 at 16 31 31" src="https://user-images.githubusercontent.com/42141299/53972337-7cb6d480-40f6-11e9-8257-96bed509b4c9.png">

**Comment by brian-learningpool** [comment]
This was an issue with the extension rather than this component.
