### ISSUE TITLE
Not working in latest Adapt Authoring; this.model[name] is not a function

### ISSUE THREAD

**Issue by 3-w-c** [LearningPool/adapt-contrib-openTextInput#54]
Steps to reproduce:

1. Download ZIP of `master` branch from this repo
2. Plugin Management » Upload Plugin » choose ZIP file
3. Add openTextInput component to a Block
4. Click "Preview" or "Export"

I get errors like this:

```
Command failed: grunt server-build:prod --outputdir=courses/5e3b46b0dd1dd61d5a15fcd8/5e62c9f228407522a2c7d7a3/build --theme=5e3b49068e8e9f1ea6e48a5d --menu=adapt-contrib-boxMenu

Fatal error: {
 "message": "variable @primary-color is undefined",
 "type": "Name",
 "filename": "src/components/adapt-contrib-openTextInput/less/opentextinput.less",
 "index": 494,
 "line": 23,
 "column": 20,
 "callLine": null,
 "extract": [
  "    .openTextInput-count-characters {",
  "        background: @primary-color;",
  "        color: @white;"
 ]
}
```

(which seems to be the same as #40)

If I edit the LESS file to change e.g. `@disabled-color` to `@disabled` then the preview loads successfully, but I get errors like this in the JS console when trying to open the page with openTextInput on it: 

```
TypeError: this.model[name] is not a function adapt.min.js:1:190580
TypeError: this.model.setQuestionAsReset is not a function adapt.min.js:1:184395
```

Any clues?

**Comment by oliverfoster** [comment]
Can you turn on debugger and print out the full error please.

**Comment by 3-w-c** [comment]
Many moons later and I'm very confused, I finally got back to this, enabled sourcemaps, and I'm no longer seeing a crash 🥳

Now I'm facing a different problem, but I can't reproduce this one so I'll close it.
